### ISSUE TITLE
Make the templates dynamically linked to known sources 

### ISSUE THREAD

**Issue by yakir12** [tpapp/skeleton.jl#12]
Some of the files in the template (and maybe parts of a file) can be improved if their content was dynamically created from some trusted known canonical source. So for example, the `.gitignore` could be created dependent on whatever is in here: https://github.com/github/gitignore/blob/master/Julia.gitignore the idea being, that you don't need to curate the content of that file, that task has already been taken care off in the "official" place for that file (disregarding if that indeed should be the official gitignore for Julia). This way, if that file ever changes then so will the file `skeleton.jl` generates on the user's machine. I agree that as time goes those changes will become more sparse, but for now, while Julia is young, this might bother you quite a bit. 

## Meta discussion
While moving the freshness of the content from when you, Tamas Papp, created the template file to when ever someone ran skeleton.jl is better, the best would have been to have the content always linked to "the cloud". This way the content would always be fresh. Rambling over.

**Comment by tpapp** [comment]
Possibly, but this is beyond the scope of this project, which I want to keep simple.

In any case, I would always want to review 3rd party content.
