### ISSUE TITLE
Copyright note

### ISSUE THREAD

**Issue by henriquebecker91** [tpapp/skeleton.jl#21]
I used the script today (Mon 03 Jun 2019 05:28:16 PM -03) and it gave me:

"> Copyright (c) 2018: Henrique Becker."

Is the year in the copyright declaration hardcoded?

**Comment by tpapp** [comment]
Yes, it is. Will fix soon.

**Comment by tpapp** [comment]
Fixed in the port https://github.com/tpapp/PkgSkeleton.jl. Will not fix here as that is replacing this package.
