### ISSUE TITLE
Using deprecated argument in docs/make.jl 

### ISSUE THREAD

**Issue by henriquebecker91** [tpapp/skeleton.jl#22]
Running the generated make.jl gives:

>┌ Warning: `format = :html` is deprecated, use `format = Documenter.HTML()` instead.
>│   caller = ip:0x0
>└ @ Core :-1

So I suppose its generation needs to be updated.

**Comment by tpapp** [comment]
Note that the docs has its [own project file](https://github.com/tpapp/skeleton.jl/blob/9a5a68e2dfa340d4bdaf5f34de84421c545be1c8/template/docs/Project.toml) which pins the version for Documenter, and is usually run with that (eg see the Travis file).

That said, I will update it at some point.

**Comment by tpapp** [comment]
This is fixed in the port https://github.com/tpapp/PkgSkeleton.jl/pull/1. Not fixing here as this project will be archived anyway.
