### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by yakir12** [tpapp/skeleton.jl#8]
Why no gitignore..?

**Comment by tpapp** [comment]
I could add one, what paths would you like to ignore?

**Comment by yakir12** [comment]
I think Julia has a "standard" gitignore somewhere.. But even having one as a place holder is better than nothing. Or maybe it departs too much from your KISS attitude ;)

**Comment by yakir12** [comment]
[here](https://github.com/github/gitignore/blob/master/Julia.gitignore)!

**Comment by phelipe** [comment]
Many packages use notebooks so it would be interesting to add
```
.ipynb_checkpoints
*/ipynb_checkpoints/*
```
to gitignore.

**Comment by tpapp** [comment]
@phelipe, this is a good suggestion but I would be conservative here leave these extras to the package developer (it is trivial to add later) and only ignore the bare minimum.
